feedback to "user interface"
SofiBretz/tic_tac_toe pull request #3
Opened 2019-10-04 19:37 UTC by thsvr

Hi,

Can you please check our code and give feedback?

Thank you in advance :)

Thaís and Sofi

2019-10-04 20:40 UTC, samgaco requested changes
Hi @SofiBretz and @thsvr :high_brightness: 

- [ ] We should be able to execute the game `ruby bin/main.rb` and see how it would look like in the console. (Of course, no real logic behind the things prompted in there). 

_Example: we execute, and we see the game asking us questions like: what is your name?, the game board being prompted and questions like, where do you want to place your move?, etc.  All the game from start to end should be mocked._

- [ ] I left some comments on things that should be mocked as well.


------------------


* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-10-04 20:40 UTC, samgaco commented on bin/main.rb
> +    puts "Players take turns putting their marks in empty squares"
this should be also mocked in here

* where is the game asking for a move to the players? 
* What are the possible moves available?
* if a player inputs a move that is not valid, how is the game going to react?

2019-10-07 20:21 UTC, SofiBretz commented
### Summary of changes made

- Linters fixed, no conflicts on this branch.

- New classes added to organized better the code of the game.

- The code is cleaner to read.

- Code executable.

2019-10-08 00:31 UTC, Ispirett requested changes
Hey!! @SofiBretz how are you?  great work @SofiBretz  @thsvr  setting up the folder structure  and welcome message  :+1:  :100: 

For this milestone, you need to have mock logic for the game. Thses are the things you should have below.

**[OPTIONAL]** 
- [ ] game ask players for their names

 **[REQUIRED]**
- [ ] game tells which player turn it is

- [ ]  game asks player to select from available moves

 - [ ]  game informs the player if the selected move is invalid

- [ ]   game displays board after the player move

- [ ] game informs the player if the selected move is a winning move

- [ ] game informs player if selected move is a draw move

- [ ]  game repeats all actions for next player's move

You don't  have to implement actual logic  you can use a ` puts "message" `
This step is to help you think through the structure of your code for the game.
you can use  a ` while loop ` to switch the turn of the players.

status: changes to be made

2019-10-08 20:50 UTC, SofiBretz commented
### Summary of changes made

Linters fixed, no conflicts on this branch.

Advices of the tse corrected.

The code is cleaner to read.

In this file, the game is not working 100% because it is necessary to link the main.rb file with the other files that we have to complete on the milestone 3.

The point here is that in the main time when we were waiting for this review, we advanced with the game and now we finished, so please contact us if you want to see the entire code working because for this milestone we can not run it 100%. But we already finished the milestone 3.

**So please before request another thing contact us first.**  Thanks for understanding us, we made to much progress already.

2019-10-10 12:46 UTC, samgaco approved these changes
Hi @SofiBretz and @thsvr 

The point of this milestone is to show the interface as it would show if the game were to be finished. At this point, it is not working (I have read your message though). Anyways, since the structure implemented looks all right and you are already working on the milestone 3 I will approve it.

Regards.

-----------------------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-10-10 12:46 UTC, samgaco commented on bin/main.rb
> +    player1 = Player.new(name_valid?(name))
the class is not defined

2019-10-10 22:23 UTC, closed without merging